### ISSUE TITLE
请问这个分词器如何自定义词库，望解答

### ISSUE THREAD

**Issue by Luna-CY** [microbun/elasticsearch-thulac-plugin#1]
RT

**Comment by shadowinlife** [comment]
同问

**Comment by shadowinlife** [comment]
@Accyl 
`public static void main(String[] args) throws IOException {
		String user_specified_dict_name=null;`
我看到的解决方法是, 在这里自己hardcode进去....

不过能不能不停机追加新词就不知道了

**Comment by microbun** [comment]
已经添加到配置中了，可以阅读说明文档
