### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by liangWenPeng** [microbun/elasticsearch-thulac-plugin#2]
java.lang.NullPointerException
at org.elasticsearch.thulac.Thulac.segment(Thulac.java:92)

**Comment by microbun** [comment]
在什么情况产生的

**Comment by microbun** [comment]
之前采用的thulac分词为v1.2版，出现了不少问题，现在用lite版重写了插件。请thulac使用lite版对应的插件，谢谢反馈。
