### ISSUE TITLE
ThulacTokenizerImpl 的逻辑可能有问题。测试了一段长文本，其中有很大一段没有被拆分成词。

### ISSUE THREAD

**Issue by yunyi-the-coder** [microbun/elasticsearch-thulac-plugin#3]
//我把测试里的文本替换成了一段很长的文本。测试结果显示有很大一段文本没有被拆分成词。具体结果运行一下下面这段代码就能看到了。

@Test
    public void test2() {
        ThulacTokenizerImpl scaner = new ThulacTokenizerImpl();
        scaner.reset(new StringReader("中国是世界上人口最多的国家，2008年底中国大陆人口13.28亿，占全世界人口的20%，也就是说全世界平均每5个人当中就有一个是黄皮肤、黑头发的中国人。为什么中国人有这么多？中国怎么解决这个问题？请让我慢慢说起。古代的时候，中国人口并不多。清朝以前，中国人口都不超过一亿，有些朝代人口甚至只有一两千万，即使最强大的唐朝，人口也只有五千万。由于古代医学比较落后，生孩子有很大的危险，很多孩子一出生就死了；古代人的生活条件也不好，有些&nbsp;家庭很穷，就算生了孩子也无法把他们养大；还有，古代人喜欢男孩儿，认为男孩儿可以劳动，而女孩儿却没有用，所以女孩儿常常被抛弃。这种重男轻女的错误思想也是造成中国古代人&nbsp;少的一个原因。农业对古代中国非常重要，而人口就是劳动力。“谁生的孩子越多，谁就越光荣”，这种思想一直保持到新中国成立。为了加快发展，政府鼓励人们多生孩子，而且现代社会的医学水平比较发达，人们的生活条件也提高了，生孩子从很困难变成很容易，最后竟然难以控制。50年里，中国人口从5亿增加到11亿，翻了一番。这个速度太快了，如果不控制，后果不堪设想。于是70年代，中国政府制定法律，实行“计划生育”。“计划生育”就是有计划地生孩子，并且尽可能保证孩子的健康。具体地说，就是一个家庭只生一个孩子。如果多生了孩子，就要受到一些处罚。到现在为止，计划生育使中国人口的增长减少了至少4亿，人口的增长速度也越来越低。但是，计划生育也带来了一些问题。其中最重要的一个，就是我们这一代孩子比较孤独，因为我们都没有兄弟姐妹。这样的孩子叫做“独生子女”。中国现在的年轻人基本上都是独生子女，他们的性格和父母那一代人不一样。他们更加独立，但是也更加自我。其次，中国人口的出生率降低了，这也就意味着，几年后中国的人口达到顶峰，然后不再增长，变得越来越少。还有一个问题是人口分布不均匀，也就是有些地方人多，有些地方人少。中国东部人口多，西部人口少。中国人口最多的一个省是河南省，人口将近一亿，平均每平方千米有600多人；而中国人口最少的一个省是西藏自治区，在那里，平均每平方千米可能都找不到一个人。如果你认为这些问题还不算大的话，请继续听我说。现在中国老人多，年轻人少；男人多，女人少。老人多是因为年轻一代都是独生子女，占总人口的比例突然少了，于是老人就显得很多。在性别比例上，据说中国男女比例是118:100，也就是说，有18个男人一出生就注定了以后找不到老婆。为了让人口发展更加自然和科学，政府也对计划生育进行修改。现在，在中国大部分地区，如果父母都是独生子女的家庭允许生第二个孩子。对于“人口老龄化”，也就是老人越来越多的问题，政府的目标就是改善社会福利，提高人们的生活质量。清朝的时候，中国人的平均寿命是33岁，而现在，中国人的平均寿命已经达到73岁。对于13亿的人口来说，这的确是一个值得骄傲的成绩。"));
        while (scaner.hasNext()) {
            Token token = scaner.next();
            System.out.println("word = " + token.getWord() + ", tag= " + token.getTag() + ", start= " + token.getStartOffset() + ", end=" + token.getEndOffset());
        }
    }

**Comment by microbun** [comment]
非常感谢，目前插件所采用的是Thulac V1.2版。根据你描述的问题，我通http://thulac.thunlp.org/ 下载Thulac V1.2 java版分词程序，测试出的运行结果也存在类似问题。

**Comment by microbun** [comment]
已经修复了分词问题，对应插件为 Thulac lite版。
